<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\MedFarLab.Api\MedFarLab.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MedfarLabs.Core" Version="1.2.169" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>











